### ISSUE TITLE
Pass recipe to mommy.make

### ISSUE THREAD

**Issue by TvoroG** [berinhard/model_mommy#381]
Hi! Thanks for this wonderful tool.

I don't know for sure is it possible to pass recipe to `mommy.make` or no. For example:
```
mommy.make(Book, author=foreign_key(author_recipe), _quantity=5) 
```
I've tried with `foreign_key` and without. It throws 
```
ValueError: Cannot assign "<model_mommy.recipe.RecipeForeignKey object at 0x7f62eb9aeac8>": "Book.author" must be a "Author" instance.
```

It would be cool to generate multiple instances of book with different authors generated by recipe.

What do you think?

**Comment by anapaulagomes** [comment]
Glad you find your way, @TvoroG. :) That's how my team is using too. I'm gonna close this issue since there is nothing left here.
